<?php

namespace Paymenter\Extensions\Servers\Proxmox\Services;

use Exception;
use Paymenter\Extensions\Servers\Proxmox\Models\Node;
use Paymenter\Extensions\Servers\Proxmox\Models\PortForward;
use Paymenter\Extensions\Servers\Proxmox\Models\Server;
use Paymenter\Extensions\Servers\Proxmox\Models\IPPool;

class NatService
{
    /**
     * 为服务器分配端口范围
     * 从 IP 池的 port_start 开始，找到下一个可用的连续范围
     */
    public function allocatePortRange(Server $server, int $portCount = 20): array
    {
        if (!$server->isNatMode()) {
            throw new Exception('Server is not in NAT mode');
        }

        $pool = $server->primaryIpv4->ipPool;
        $portStart = $pool->port_start;
        $poolEnd = $pool->port_end;

        // 找到该 IP 池中已分配的最大端口范围结束位置
        $maxUsedPort = Server::where('primary_ipv4', '!=', null)
            ->whereHas('primaryIpv4', function ($query) use ($pool) {
                $query->where('ip_pool_id', $pool->id);
            })
            ->whereNotNull('port_range_end')
            ->max('port_range_end');

        // 计算新的端口范围
        if ($maxUsedPort) {
            $newStart = $maxUsedPort + 1;
        } else {
            $newStart = $portStart;
        }

        $newEnd = $newStart + $portCount - 1;

        // 检查是否超出范围
        if ($newEnd > $poolEnd) {
            throw new Exception("Not enough ports available. Pool range: {$portStart}-{$poolEnd}, Requested: {$newStart}-{$newEnd}");
        }

        // 更新服务器的端口范围
        $server->port_range_start = $newStart;
        $server->port_range_end = $newEnd;
        $server->save();

        return [$newStart, $newEnd];
    }
    /**
     * 通过 SSH 连接到节点执行命令
     */
    public function executeSshCommand(Node $node, string $command): string
    {
        $host = $node->ssh_host ?: $this->extractHostFromLocation($node);
        $port = $node->ssh_port ?? 22;
        $password = $node->ssh_password;

        if (empty($password)) {
            throw new Exception('SSH password not configured for node: ' . $node->name);
        }

        // 使用 PHP 的 ssh2 扩展
        $connection = @ssh2_connect($host, $port);
        if (!$connection) {
            throw new Exception("SSH connection failed to {$host}:{$port}");
        }

        if (!@ssh2_auth_password($connection, 'root', $password)) {
            throw new Exception("SSH authentication failed for node: {$node->name}");
        }

        $stream = ssh2_exec($connection, $command);
        if (!$stream) {
            throw new Exception("SSH command execution failed: {$command}");
        }

        stream_set_blocking($stream, true);
        $output = stream_get_contents($stream);
        fclose($stream);

        return $output;
    }

    /**
     * 从 Location 的 host 字段提取主机地址
     */
    private function extractHostFromLocation(Node $node): string
    {
        $host = $node->location->host;
        // 移除协议
        $host = preg_replace('/^https?:\/\//', '', $host);
        // 移除端口
        $host = preg_replace('/:\d+$/', '', $host);
        return $host;
    }

    /**
     * 执行多条 iptables 命令
     */
    public function executeIptablesRules(Node $node, array $rules): bool
    {
        if (empty($rules)) {
            return true;
        }

        // 组合所有命令
        $command = implode(' && ', $rules);
        
        try {
            $this->executeSshCommand($node, $command);
            
            // 保存 iptables 规则
            $this->saveIptablesRules($node);
            
            return true;
        } catch (Exception $e) {
            throw new Exception("Failed to execute iptables rules: " . $e->getMessage());
        }
    }

    /**
     * 保存 iptables 规则到持久化文件，确保开机自动加载
     */
    public function saveIptablesRules(Node $node): void
    {
        // 保存规则到标准位置
        $saveCommands = [
            // 保存到 Debian/Ubuntu iptables-persistent 位置
            'mkdir -p /etc/iptables && iptables-save > /etc/iptables/rules.v4 2>/dev/null || true',
            // 保存到通用位置
            'iptables-save > /etc/iptables.rules 2>/dev/null || true',
        ];

        // 创建开机自动加载脚本
        $bootScript = '#!/bin/sh
# Auto-generated by Paymenter Proxmox NAT
if [ -f /etc/iptables/rules.v4 ]; then
    iptables-restore < /etc/iptables/rules.v4
elif [ -f /etc/iptables.rules ]; then
    iptables-restore < /etc/iptables.rules
fi
# Ensure IP forwarding is enabled
echo 1 > /proc/sys/net/ipv4/ip_forward
';

        // 写入开机脚本
        $bootScriptCommands = [
            // 创建 if-pre-up 脚本 (Debian/Ubuntu)
            'cat > /etc/network/if-pre-up.d/iptables << \'EOFSCRIPT\'
' . $bootScript . 'EOFSCRIPT',
            'chmod +x /etc/network/if-pre-up.d/iptables 2>/dev/null || true',
            // 确保 IP 转发在重启后保持
            'grep -q "net.ipv4.ip_forward" /etc/sysctl.conf || echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf',
        ];

        foreach (array_merge($saveCommands, $bootScriptCommands) as $cmd) {
            try {
                $this->executeSshCommand($node, $cmd);
            } catch (Exception $e) {
                // 忽略保存错误，继续尝试
                \Log::warning("Failed to save iptables rules: " . $e->getMessage());
            }
        }
    }

    /**
     * 为服务器分配端口转发
     */
    public function allocatePorts(Server $server, int $count): array
    {
        if (!$server->isNatMode()) {
            throw new Exception('Server is not in NAT mode');
        }

        $pool = $server->primaryIpv4->ipPool;
        $ports = $pool->getNextAvailablePorts($count);

        if (!$ports) {
            throw new Exception("Not enough available ports. Need {$count}, available: {$pool->available_port_count}");
        }

        $internalIp = $server->primaryIpv4->ip;
        $portForwards = [];
        $rules = [];

        foreach ($ports as $port) {
            $pf = PortForward::create([
                'server_id' => $server->id,
                'ip_pool_id' => $pool->id,
                'protocol' => 'both',
                'external_port' => $port,
                'internal_port' => $port,
                'internal_ip' => $internalIp,
                'description' => 'Auto assigned',
            ]);

            $portForwards[] = $pf;
            $rules = array_merge($rules, $pf->toIptablesAddRules());
        }

        // 执行 iptables 规则
        if (!empty($rules)) {
            $this->executeIptablesRules($server->node, $rules);
        }

        return $portForwards;
    }

    /**
     * 添加单个端口转发
     */
    public function addPortForward(
        Server $server,
        int $externalPort,
        int $internalPort,
        string $protocol = 'both',
        ?string $description = null
    ): PortForward {
        if (!$server->isNatMode()) {
            throw new Exception('Server is not in NAT mode');
        }

        $pool = $server->primaryIpv4->ipPool;

        // 检查端口是否在范围内
        if ($externalPort < $pool->port_start || $externalPort > $pool->port_end) {
            throw new Exception("External port must be between {$pool->port_start} and {$pool->port_end}");
        }

        // 检查端口是否已被使用
        $exists = PortForward::where('ip_pool_id', $pool->id)
            ->where('external_port', $externalPort)
            ->where('protocol', $protocol)
            ->exists();

        if ($exists) {
            throw new Exception("Port {$externalPort} is already in use");
        }

        $pf = PortForward::create([
            'server_id' => $server->id,
            'ip_pool_id' => $pool->id,
            'protocol' => $protocol,
            'external_port' => $externalPort,
            'internal_port' => $internalPort,
            'internal_ip' => $server->primaryIpv4->ip,
            'description' => $description,
        ]);

        // 执行 iptables 规则
        $this->executeIptablesRules($server->node, $pf->toIptablesAddRules());

        return $pf;
    }

    /**
     * 更新端口转发的内部端口
     */
    public function updatePortForward(PortForward $pf, int $newInternalPort): PortForward
    {
        $server = $pf->server;
        $node = $server->node;

        // 先删除旧规则
        $this->executeIptablesRules($node, $pf->toIptablesDeleteRules());

        // 更新端口
        $pf->internal_port = $newInternalPort;
        $pf->save();

        // 添加新规则
        $this->executeIptablesRules($node, $pf->toIptablesAddRules());

        return $pf;
    }

    /**
     * 删除单个端口转发
     */
    public function removePortForward(PortForward $pf): bool
    {
        $node = $pf->server->node;

        // 删除 iptables 规则
        $this->executeIptablesRules($node, $pf->toIptablesDeleteRules());

        // 删除数据库记录
        $pf->delete();

        return true;
    }

    /**
     * 删除服务器的所有端口转发
     */
    public function removeAllPortForwards(Server $server): bool
    {
        $portForwards = $server->portForwards()->get();

        if ($portForwards->isEmpty()) {
            return true;
        }

        $rules = [];
        foreach ($portForwards as $pf) {
            $rules = array_merge($rules, $pf->toIptablesDeleteRules());
        }

        // 执行删除规则
        if (!empty($rules)) {
            try {
                $this->executeIptablesRules($server->node, $rules);
            } catch (Exception $e) {
                // 记录错误但继续删除数据库记录
                \Log::warning("Failed to remove iptables rules for server {$server->id}: " . $e->getMessage());
            }
        }

        // 删除所有数据库记录
        $server->portForwards()->delete();

        return true;
    }

    /**
     * 同步服务器的所有端口转发规则（重新应用）
     */
    public function syncPortForwards(Server $server): bool
    {
        $portForwards = $server->portForwards()->where('is_active', true)->get();

        if ($portForwards->isEmpty()) {
            return true;
        }

        $rules = [];
        foreach ($portForwards as $pf) {
            $rules = array_merge($rules, $pf->toIptablesAddRules());
        }

        $this->executeIptablesRules($server->node, $rules);

        return true;
    }

    /**
     * 检查服务器是否还有可用端口配额
     */
    public function hasAvailablePortQuota(Server $server): bool
    {
        $maxPorts = $server->portCountSetting;
        $usedPorts = $server->portForwards()->count();

        return $usedPorts < $maxPorts;
    }

    /**
     * 获取服务器剩余端口配额
     */
    public function getRemainingPortQuota(Server $server): int
    {
        $maxPorts = $server->portCountSetting;
        $usedPorts = $server->portForwards()->count();

        return max(0, $maxPorts - $usedPorts);
    }

    /**
     * 初始化节点的 NAT 基础规则
     */
    public function initializeNatRules(Node $node, IPPool $pool): void
    {
        if (!$pool->is_nat) {
            return;
        }

        $interface = $pool->nat_interface;

        // 基础 NAT 规则
        $rules = [
            // 启用 IP 转发
            'echo 1 > /proc/sys/net/ipv4/ip_forward',
            // 确保 FORWARD 链默认策略
            'iptables -P FORWARD ACCEPT',
            // 添加 MASQUERADE 规则（如果不存在）
            "iptables -t nat -C POSTROUTING -o {$interface} -j MASQUERADE 2>/dev/null || " .
            "iptables -t nat -A POSTROUTING -o {$interface} -j MASQUERADE",
        ];

        $this->executeIptablesRules($node, $rules);
    }
}
